version: '3.4'
services:
  uvdesk:
    image: uvdesk/community-edition
    environment:
      UVDESK_APP_BASE_URL: "https://<your-domain>"
      UVDESK_APP_DB_HOST: db
      UVDESK_APP_DB_PORT: 3306
      UVDESK_APP_DB_NAME: uvdesk
      UVDESK_APP_DB_USER: uvdesk
      UVDESK_APP_DB_PASSWORD: "<your-password>"
      UVDESK_APP_MAILER_FROM_EMAIL: "support@<your-domain>"
      UVDESK_APP_MAILER_FROM_NAME: "UVdesk Support"
      UVDESK_APP_MAILER_HOST: "<your-mail-server-host>"
      UVDESK_APP_MAILER_PORT: "<your-mail-server-port>"
      UVDESK_APP_MAILER_USERNAME: "<your-mail-server-username>"
      UVDESK_APP_MAILER_PASSWORD: "<your-mail-server-password>"
    ports:
      - 80:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uvdesk.rule=Host(`<your-domain>`)"
      - "traefik.http.routers.uvdesk.entrypoints=websecure"
      - "traefik.http.routers.uvdesk.tls=true"
      - "traefik.http.services.uvdesk.loadbalancer.server.port=80"
    depends_on:
      - db
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: uvdesk
      MYSQL_USER: uvdesk
      MYSQL_PASSWORD: "<your-password>"
      MYSQL_ROOT_PASSWORD: "<your-root-password>"
    ports:
      - 3306:3306
